version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/delivery
    ports:
      - "80:3000"
    depends_on:
      - postgres
    env_file:
      - .env